---
- name: "firewall: install firewalld"
  ansible.builtin.package:
    name: firewalld
    state: present

- name: "firewall: enable firewalld.service"
  ansible.builtin.command: systemctl enable firewalld.service
  register: enable_result
  changed_when: "'Created symlink' in enable_result.stderr or 'Created symlink' in enable_result.stdout"
