---
- name: "bluetooth: install bluez"
  ansible.builtin.package:
    name:
      - bluez
      - bluez-utils
    state: present

- name: "bluetooth: enable bluetooth.service"
  ansible.builtin.command: systemctl enable bluetooth.service
  register: enable_result
  changed_when: "'Created symlink' in enable_result.stderr or 'Created symlink' in enable_result.stdout"
